name: Hello World Workflow
on:
  push

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        env:
          printable: World
        run: "echo 'Hello $printable'"
