name: Hello World Workflow
on:
  push

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        env:
          printable: World
        run: echo "Hello ${{env.printable}}"
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: calling composite action
        id: calling-action-step
        uses: ./.github/workflows
        with:
          action_input: Ravi
      - name: print called action output
        run: echo "Random Number --> $random_output"
        env:
          random_output: ${{steps.calling-action-step.outputs.action_output}}

